// import Footer from "@/Footer";
// import Header from "@/Header";
import * as React from "react";
import Header from "./Header";
import Footer from "./Footer";
import { Fab } from "@mui/material";
import ArrowUpwardIcon from "@mui/icons-material/ArrowUpward";

// export const metadata = {
//   title: "Barun it solutions",
//   description: "Generated by core developers",
// };

export default function Layout({ children }) {
  const handleScrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer/>
        <Fab
          color="primary"
          style={{
            position: "fixed",
            bottom: "30px",
            right: "30px",
          }}
          onClick={handleScrollToTop}
        >
          <ArrowUpwardIcon /></Fab>      </body>
    </html>
  );
}
